name: Expo Preview

on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Expo CLI
        run: npm install --global expo eas-cli

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Expo Preview Action
        uses: expo/expo-preview-action@v1.2.2
        with:
          working-directory: frontend
          project-root: frontend
